import type { Circuit, Program } from '../types'

function circuit(c: Circuit): Circuit {
  return c
}

export function buildSeedProgram(): Program {
  return {
    id: 'programme-1',
    name: 'Programme Papa',
    sessions: [
      {
        id: 'mardi',
        name: 'Mardi — Mobilité + Prévention full body + abdo',
        circuits: [
          circuit({
            id: 'p-mar-c1',
            name: 'Mobilité',
            tours: 3,
            repos: 60,
            exercises: [
              {
                id: 'p-mar-1',
                video: 'p-mar-1.mp4',
                name: 'Contraction + assouplissement bras tendu',
                reps: '5 x (5s/5s) / bras',
                note: 'Bras tendu devant toi : contracte 5s puis relâche/étire 5s, alterne par bras.',
              },
              {
                id: 'p-mar-2',
                video: 'p-mar-2.mp4',
                name: 'Circle',
                reps: '6',
                note: "Allongé au sol, trace un grand cercle avec le bras en cherchant l'amplitude max : va devant puis repars derrière, rotation du poignet à 180° au milieu.",
              },
              {
                id: 'p-mar-3',
                video: 'p-mar-3.mp4',
                name: 'Squat profond',
                reps: '30-45s',
                unit: 'secondes',
                note: 'Descends en squat complet et reste en bas, dos droit, le temps indiqué.',
              },
            ],
          }),
          circuit({
            id: 'p-mar-c2',
            name: 'Renfo + Prévention',
            tours: 3,
            repos: 120,
            intensite: 'RPE 7',
            exercises: [
              {
                id: 'p-mar-4',
                video: 'p-mar-4.mp4',
                name: 'Iso fentes bulgare + traction élastique',
                reps: '30-45s',
                unit: 'secondes',
                note: "Fente bulgare tenue en isométrie ; élastique fixé au niveau du genou qui tire vers l'intérieur — résiste pour garder le genou aligné.",
              },
              {
                id: 'p-mar-5',
                video: 'p-mar-5.mp4',
                name: 'Ponté pelvien + abduction',
                reps: '12',
                note: 'Pont fessier au sol, écarte les genoux (élastique) en haut du mouvement.',
              },
              {
                id: 'p-mar-6',
                video: 'p-mar-6.mp4',
                name: 'Dead bug',
                reps: '16-20',
                note: 'Allongé sur le dos, bas du dos plaqué au sol, étends bras et jambe opposés en alternance.',
              },
              {
                id: 'p-mar-7',
                video: 'p-mar-7.mp4',
                name: 'Planche latérale + tirage',
                reps: '10/côté',
                note: "Gainage latéral + tirage (rowing) avec l'élastique du bras libre.",
              },
              {
                id: 'p-mar-8',
                video: 'p-mar-8.mp4',
                name: 'Palof press OH',
                reps: '10/côté',
                note: 'Élastique tendu sur le côté : pousse les bras au-dessus de la tête en résistant à la rotation.',
              },
            ],
          }),
        ],
      },
      {
        id: 'jeudi',
        name: 'Jeudi — Mobilité + renfo full body',
        circuits: [
          circuit({
            id: 'p-jeu-c1',
            name: 'Mobilité',
            tours: 3,
            repos: 60,
            exercises: [
              {
                id: 'p-jeu-1',
                video: 'p-jeu-1.mp4',
                name: 'RE / RI au sol',
                reps: '5 x (5s/5s) / bras',
                note: "Allongé sur le côté, bras à 90° de l'épaule : pousse 5s vers le bas (rotation interne) puis 5s vers le haut (rotation externe).",
              },
              {
                id: 'p-jeu-2',
                video: 'p-jeu-2.mp4',
                name: 'Pigeon pose dynamique',
                reps: '5 x 5s amplitude max',
                note: "Posture du pigeon en mouvement répété, cherche l'amplitude max à chaque répétition.",
              },
              {
                id: 'p-jeu-3',
                video: 'p-jeu-3.mp4',
                name: 'Superman',
                reps: '20-30s',
                unit: 'secondes',
                note: 'Ventre au sol, lève bras et jambes tendus et maintiens.',
              },
            ],
          }),
          circuit({
            id: 'p-jeu-c2',
            name: 'Renfo + Prévention',
            tours: 3,
            repos: 120,
            intensite: 'RPE 8',
            exercises: [
              {
                id: 'p-jeu-4',
                video: 'p-jeu-4.mp4',
                name: 'Tirage + R2 OH',
                reps: '12/bras',
                note: 'Tirage (rowing) classique puis termine en montant la main au-dessus de la tête.',
              },
              {
                id: 'p-jeu-5',
                video: 'p-jeu-5.mp4',
                name: 'Pompes excentrique',
                reps: '10',
                note: 'Pompes en ralentissant la descente au maximum.',
              },
              {
                id: 'p-jeu-6',
                video: 'p-jeu-6.mp4',
                name: 'Pistol excentrique sur banc',
                reps: '6/côté',
                note: 'Squat une jambe assisté par le banc, descente contrôlée.',
              },
              {
                id: 'p-jeu-7',
                video: 'p-jeu-7.mp4',
                name: 'Monster walk',
                reps: '10/côté',
                note: 'Élastique aux chevilles/genoux, marche latérale en squat partiel.',
              },
            ],
          }),
        ],
      },
      {
        id: 'samedi',
        name: 'Samedi — Mobilité + renfo full body',
        circuits: [
          circuit({
            id: 'p-sam-c1',
            name: 'Mobilité',
            tours: 3,
            repos: 90,
            exercises: [
              {
                id: 'p-sam-1',
                video: 'p-sam-1.mp4',
                name: 'Cars hanche',
                reps: '6/côté',
                note: "Rotation articulaire contrôlée de la hanche : cherche l'amplitude max dans tous les sens.",
              },
              {
                id: 'p-sam-2',
                video: 'p-sam-2.mp4',
                name: 'Contraction + assouplissement bras tendu',
                reps: '5 x (5s/5s) / bras',
                note: 'Bras tendu devant toi : contracte 5s puis relâche/étire 5s, alterne par bras.',
              },
              {
                id: 'p-sam-3',
                video: 'p-sam-3.mp4',
                name: 'OH squat avec élastique',
                reps: '10',
                note: 'Squat bras tendus au-dessus de la tête, élastique placé autour des genoux.',
              },
            ],
          }),
          circuit({
            id: 'p-sam-c2',
            name: 'Renfo + Prévention',
            tours: 3,
            repos: 120,
            intensite: 'RPE 7',
            exercises: [
              {
                id: 'p-sam-4',
                video: 'p-sam-4.mp4',
                name: 'Bird dog',
                reps: '8/côté',
                note: 'Quadrupédie, étends bras et jambe opposés en gardant le dos stable.',
              },
              {
                id: 'p-sam-5',
                video: 'p-sam-5.mp4',
                name: 'Tirage bûcheron controlatéral',
                reps: '10/côté',
                note: 'Genou droit sur le banc, main droite qui tire, jambe gauche tendue en arrière, ramène le coude vers la hanche.',
              },
              {
                id: 'p-sam-6',
                video: 'p-sam-6.mp4',
                name: 'Écarté haltère',
                reps: '10',
                note: 'Couché sur le banc, écarté avec haltères pour les pectoraux.',
              },
              {
                id: 'p-sam-7',
                video: 'p-sam-7.mp4',
                name: 'Hollow',
                reps: '20-40s',
                unit: 'secondes',
                note: 'Allongé, bras et jambes légèrement levés, bas du dos plaqué au sol.',
              },
            ],
          }),
        ],
      },
      {
        id: 'etirements',
        name: 'Étirements (quand tu veux)',
        circuits: [
          circuit({
            id: 'etir-c1',
            name: 'Étirements complets',
            tours: 1,
            repos: 0,
            exercises: [
              {
                id: 'etir-1',
                video: 'etir-1.mp4',
                name: 'Pectoraux',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Bras plié, coude contre le mur à hauteur d\'épaule, tourne le buste vers l\'opposé pour étirer.',
              },
              {
                id: 'etir-2',
                video: 'etir-2.mp4',
                name: 'Triceps',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Bras au-dessus de la tête, coude plié, main derrière la nuque, pousse doucement avec l\'autre main.',
              },
              {
                id: 'etir-3',
                video: 'etir-3.mp4',
                name: 'Grand dorsal',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Bras en rotation externe à 90°, main posée contre le mur, descends le buste.',
              },
              {
                id: 'etir-4',
                video: 'etir-4.mp4',
                name: 'Lombaires',
                reps: '30',
                unit: 'secondes',
                note: "Posture de l'enfant (child pose).",
              },
              {
                id: 'etir-5',
                video: 'etir-5.mp4',
                name: 'Fessiers',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Pied posé au-dessus de la cuisse opposée, tire la jambe vers toi.',
              },
              {
                id: 'etir-6',
                video: 'etir-6.mp4',
                name: 'Piriforme',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Même principe mais pied au-dessus du genou opposé.',
              },
              {
                id: 'etir-7',
                video: 'etir-7.mp4',
                name: 'Ischio-jambiers',
                reps: '30/côté',
                unit: 'secondes',
                note: "Une jambe pliée (pied au niveau de l'adducteur), l'autre jambe tendue, cherche à atteindre le pied.",
              },
              {
                id: 'etir-8',
                video: 'etir-8.mp4',
                name: 'Adducteurs',
                reps: '30',
                unit: 'secondes',
                note: 'Papillon : plantes de pieds jointes, genoux qui descendent vers le sol.',
              },
              {
                id: 'etir-9',
                video: 'etir-9.mp4',
                name: 'Pigeon pose',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Posture du pigeon (hanche/fessier).',
              },
              {
                id: 'etir-10',
                video: 'etir-10.mp4',
                name: 'Mollets',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Debout, une jambe part loin derrière, talon au sol.',
              },
              {
                id: 'etir-11',
                video: 'etir-11.mp4',
                name: 'Quadriceps',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Assis, une jambe pliée en arrière (pied à côté de la hanche), buste droit, pas de bascule en arrière.',
              },
              {
                id: 'etir-12',
                video: 'etir-12.mp4',
                name: 'Psoas (fléchisseurs de hanche)',
                reps: '30/côté',
                unit: 'secondes',
                note: 'Fente, genou arrière au sol, avance le bassin en gardant le dos droit, légère rotation du buste vers le côté opposé à la jambe arrière.',
              },
            ],
          }),
        ],
      },
    ],
  }
}
