import type { Exercise, Program } from '../types'

function ex(partial: Omit<Exercise, 'id'> & { id: string }): Exercise {
  return partial
}

export function buildSeedProgram(): Program {
  return {
    id: 'programme-1',
    name: 'Programme Papa',
    sessions: [
      {
        id: 'mardi',
        name: 'Mardi — Mobilité + Prévention full body + abdo',
        exercises: [
          ex({
            id: 'p-mar-1',
            name: 'Contraction + assouplissement bras tendu',
            sets: 3,
            reps: '5 x (5s/5s) / bras',
            repos: 60,
            note: 'Bras tendu devant toi : contracte 5s puis relâche/étire 5s, alterne par bras.',
          }),
          ex({
            id: 'p-mar-2',
            name: 'Circle',
            sets: 3,
            reps: '6',
            repos: 60,
            note: "Allongé au sol, trace un grand cercle avec le bras en cherchant l'amplitude max : va devant puis repars derrière, rotation du poignet à 180° au milieu.",
          }),
          ex({
            id: 'p-mar-3',
            name: 'Squat profond',
            sets: 3,
            reps: '30-45s',
            repos: 60,
            note: 'Descends en squat complet et reste en bas, dos droit, le temps indiqué.',
          }),
          ex({
            id: 'p-mar-4',
            name: 'Iso fentes bulgare + traction élastique',
            sets: 3,
            reps: '30-45s',
            repos: 120,
            intensite: 'RPE 7',
            note: "Fente bulgare tenue en isométrie ; élastique fixé au niveau du genou qui tire vers l'intérieur — résiste pour garder le genou aligné.",
          }),
          ex({
            id: 'p-mar-5',
            name: 'Ponté pelvien + abduction',
            sets: 3,
            reps: '12',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Pont fessier au sol, écarte les genoux (élastique) en haut du mouvement.',
          }),
          ex({
            id: 'p-mar-6',
            name: 'Dead bug',
            sets: 3,
            reps: '16-20',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Allongé sur le dos, bas du dos plaqué au sol, étends bras et jambe opposés en alternance.',
          }),
          ex({
            id: 'p-mar-7',
            name: 'Planche latérale + tirage',
            sets: 3,
            reps: '10/côté',
            repos: 120,
            intensite: 'RPE 7',
            note: "Gainage latéral + tirage (rowing) avec l'élastique du bras libre.",
          }),
          ex({
            id: 'p-mar-8',
            name: 'Palof press OH',
            sets: 3,
            reps: '10/côté',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Élastique tendu sur le côté : pousse les bras au-dessus de la tête en résistant à la rotation.',
          }),
        ],
      },
      {
        id: 'jeudi',
        name: 'Jeudi — Mobilité + renfo full body',
        exercises: [
          ex({
            id: 'p-jeu-1',
            name: 'RE / RI au sol',
            sets: 3,
            reps: '5 x (5s/5s) / bras',
            repos: 60,
            note: 'Allongé sur le côté, bras à 90° de l\'épaule : pousse 5s vers le bas (rotation interne) puis 5s vers le haut (rotation externe).',
          }),
          ex({
            id: 'p-jeu-2',
            name: 'Pigeon pose dynamique',
            sets: 3,
            reps: '5 x 5s amplitude max',
            repos: 60,
            note: "Posture du pigeon en mouvement répété, cherche l'amplitude max à chaque répétition.",
          }),
          ex({
            id: 'p-jeu-3',
            name: 'Superman',
            sets: 3,
            reps: '20-30s',
            repos: 60,
            note: 'Ventre au sol, lève bras et jambes tendus et maintiens.',
          }),
          ex({
            id: 'p-jeu-4',
            name: 'Tirage + R2 OH',
            sets: 3,
            reps: '12/bras',
            repos: 120,
            intensite: 'RPE 8',
            note: 'Tirage (rowing) classique puis termine en montant la main au-dessus de la tête.',
          }),
          ex({
            id: 'p-jeu-5',
            name: 'Pompes excentrique',
            sets: 3,
            reps: '10',
            repos: 120,
            intensite: 'RPE 8',
            note: 'Pompes en ralentissant la descente au maximum.',
          }),
          ex({
            id: 'p-jeu-6',
            name: 'Pistol excentrique sur banc',
            sets: 3,
            reps: '6/côté',
            repos: 120,
            intensite: 'RPE 8',
            note: 'Squat une jambe assisté par le banc, descente contrôlée.',
          }),
          ex({
            id: 'p-jeu-7',
            name: 'Monster walk',
            sets: 3,
            reps: '10/côté',
            repos: 120,
            intensite: 'RPE 8',
            note: 'Élastique aux chevilles/genoux, marche latérale en squat partiel.',
          }),
        ],
      },
      {
        id: 'samedi',
        name: 'Samedi — Mobilité + renfo full body',
        exercises: [
          ex({
            id: 'p-sam-1',
            name: 'Cars hanche',
            sets: 3,
            reps: '6/côté',
            repos: 90,
            note: "Rotation articulaire contrôlée de la hanche : cherche l'amplitude max dans tous les sens.",
          }),
          ex({
            id: 'p-sam-2',
            name: 'Contraction + assouplissement bras tendu',
            sets: 3,
            reps: '5 x (5s/5s) / bras',
            repos: 90,
            note: 'Bras tendu devant toi : contracte 5s puis relâche/étire 5s, alterne par bras.',
          }),
          ex({
            id: 'p-sam-3',
            name: 'OH squat avec élastique',
            sets: 3,
            reps: '10',
            repos: 90,
            note: 'Squat bras tendus au-dessus de la tête, élastique placé autour des genoux.',
          }),
          ex({
            id: 'p-sam-4',
            name: 'Bird dog',
            sets: 3,
            reps: '8/côté',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Quadrupédie, étends bras et jambe opposés en gardant le dos stable.',
          }),
          ex({
            id: 'p-sam-5',
            name: 'Tirage bûcheron controlatéral',
            sets: 3,
            reps: '10/côté',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Genou droit sur le banc, main droite qui tire, jambe gauche tendue en arrière, ramène le coude vers la hanche.',
          }),
          ex({
            id: 'p-sam-6',
            name: 'Écarté haltère',
            sets: 3,
            reps: '10',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Couché sur le banc, écarté avec haltères pour les pectoraux.',
          }),
          ex({
            id: 'p-sam-7',
            name: 'Hollow',
            sets: 3,
            reps: '20-40s',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Allongé, bras et jambes légèrement levés, bas du dos plaqué au sol.',
          }),
        ],
      },
    ],
  }
}
